// Windows NT NTFS Standard Upcase Table
// Contains full 64K Unicode character mappings matching Windows NT kernel RtlUpcaseUnicodeChar

const NT_UPCASE_PAIRS_B64 = 'YQBBAGIAQgBjAEMAZABEAGUARQBmAEYAZwBHAGgASABpAEkAagBKAGsASwBsAEwAbQBNAG4ATgBvAE8AcABQAHEAUQByAFIAcwBTAHQAVAB1AFUAdgBWAHcAVwB4AFgAeQBZAHoAWgDgAMAA4QDBAOIAwgDjAMMA5ADEAOUAxQDmAMYA5wDHAOgAyADpAMkA6gDKAOsAywDsAMwA7QDNAO4AzgDvAM8A8ADQAPEA0QDyANIA8wDTAPQA1AD1ANUA9gDWAPgA2AD5ANkA+gDaAPsA2wD8ANwA/QDdAP4A3gD/AHgBAQEAAQMBAgEFAQQBBwEGAQkBCAELAQoBDQEMAQ8BDgERARABEwESARUBFAEXARYBGQEYARsBGgEdARwBHwEeASEBIAEjASIBJQEkAScBJgEpASgBKwEqAS0BLAEvAS4BMwEyATUBNAE3ATYBOgE5ATwBOwE+AT0BQAE/AUIBQQFEAUMBRgFFAUgBRwFLAUoBTQFMAU8BTgFRAVABUwFSAVUBVAFXAVYBWQFYAVsBWgFdAVwBXwFeAWEBYAFjAWIBZQFkAWcBZgFpAWgBawFqAW0BbAFvAW4BcQFwAXMBcgF1AXQBdwF2AXoBeQF8AXsBfgF9AYABQwKDAYIBhQGEAYgBhwGMAYsBkgGRAZUB9gGZAZgBmgE9Ap4BIAKhAaABowGiAaUBpAGoAacBrQGsAbABrwG0AbMBtgG1AbkBuAG9AbwBvwH3AcYBxAHJAccBzAHKAc4BzQHQAc8B0gHRAdQB0wHWAdUB2AHXAdoB2QHcAdsB3QGOAd8B3gHhAeAB4wHiAeUB5AHnAeYB6QHoAesB6gHtAewB7wHuAfMB8QH1AfQB+QH4AfsB+gH9AfwB/wH+AQECAAIDAgICBQIEAgcCBgIJAggCCwIKAg0CDAIPAg4CEQIQAhMCEgIVAhQCFwIWAhkCGAIbAhoCHQIcAh8CHgIjAiICJQIkAicCJgIpAigCKwIqAi0CLAIvAi4CMQIwAjMCMgI8AjsCQgJBAkcCRgJJAkgCSwJKAk0CTAJPAk4CUAJvLFECbSxTAoEBVAKGAVYCiQFXAooBWQKPAVsCkAFgApMBYwKUAWgClwFpApYBawJiLG8CnAFxAm4scgKdAXUCnwF9AmQsgAKmAYMCqQGIAq4BiQJEAooCsQGLArIBjAJFApICtwFxA3ADcwNyA3cDdgN7A/0DfAP+A30D/wOsA4YDrQOIA64DiQOvA4oDsQORA7IDkgOzA5MDtAOUA7UDlQO2A5YDtwOXA7gDmAO5A5kDugOaA7sDmwO8A5wDvQOdA74DngO/A58DwAOgA8EDoQPDA6MDxAOkA8UDpQPGA6YDxwOnA8gDqAPJA6kDygOqA8sDqwPMA4wDzQOOA84DjwPXA88D2QPYA9sD2gPdA9wD3wPeA+ED4APjA+ID5QPkA+cD5gPpA+gD6wPqA+0D7APvA+4D8gP5A/gD9wP7A/oDMAQQBDEEEQQyBBIEMwQTBDQEFAQ1BBUENgQWBDcEFwQ4BBgEOQQZBDoEGgQ7BBsEPAQcBD0EHQQ+BB4EPwQfBEAEIARBBCEEQgQiBEMEIwREBCQERQQlBEYEJgRHBCcESAQoBEkEKQRKBCoESwQrBEwELARNBC0ETgQuBE8ELwRQBAAEUQQBBFIEAgRTBAMEVAQEBFUEBQRWBAYEVwQHBFgECARZBAkEWgQKBFsECwRcBAwEXQQNBF4EDgRfBA8EYQRgBGMEYgRlBGQEZwRmBGkEaARrBGoEbQRsBG8EbgRxBHAEcwRyBHUEdAR3BHYEeQR4BHsEegR9BHwEfwR+BIEEgASLBIoEjQSMBI8EjgSRBJAEkwSSBJUElASXBJYEmQSYBJsEmgSdBJwEnwSeBKEEoASjBKIEpQSkBKcEpgSpBKgEqwSqBK0ErASvBK4EsQSwBLMEsgS1BLQEtwS2BLkEuAS7BLoEvQS8BL8EvgTCBMEExATDBMYExQTIBMcEygTJBMwEywTOBM0EzwTABNEE0ATTBNIE1QTUBNcE1gTZBNgE2wTaBN0E3ATfBN4E4QTgBOME4gTlBOQE5wTmBOkE6ATrBOoE7QTsBO8E7gTxBPAE8wTyBPUE9AT3BPYE+QT4BPsE+gT9BPwE/wT+BAEFAAUDBQIFBQUEBQcFBgUJBQgFCwUKBQ0FDAUPBQ4FEQUQBRMFEgUVBRQFFwUWBRkFGAUbBRoFHQUcBR8FHgUhBSAFIwUiBWEFMQViBTIFYwUzBWQFNAVlBTUFZgU2BWcFNwVoBTgFaQU5BWoFOgVrBTsFbAU8BW0FPQVuBT4FbwU/BXAFQAVxBUEFcgVCBXMFQwV0BUQFdQVFBXYFRgV3BUcFeAVIBXkFSQV6BUoFewVLBXwFTAV9BU0FfgVOBX8FTwWABVAFgQVRBYIFUgWDBVMFhAVUBYUFVQWGBVYFeR19p30dYywBHgAeAx4CHgUeBB4HHgYeCR4IHgseCh4NHgweDx4OHhEeEB4THhIeFR4UHhceFh4ZHhgeGx4aHh0eHB4fHh4eIR4gHiMeIh4lHiQeJx4mHikeKB4rHioeLR4sHi8eLh4xHjAeMx4yHjUeNB43HjYeOR44HjseOh49HjwePx4+HkEeQB5DHkIeRR5EHkceRh5JHkgeSx5KHk0eTB5PHk4eUR5QHlMeUh5VHlQeVx5WHlkeWB5bHloeXR5cHl8eXh5hHmAeYx5iHmUeZB5nHmYeaR5oHmseah5tHmwebx5uHnEecB5zHnIedR50Hncedh55Hngeex56Hn0efB5/Hn4egR6AHoMegh6FHoQehx6GHokeiB6LHooejR6MHo8ejh6RHpAekx6SHpUelB6hHqAeox6iHqUepB6nHqYeqR6oHqseqh6tHqwerx6uHrEesB6zHrIetR60Hrceth65Hrgeux66Hr0evB6/Hr4ewR7AHsMewh7FHsQexx7GHskeyB7LHsoezR7MHs8ezh7RHtAe0x7SHtUe1B7XHtYe2R7YHtse2h7dHtwe3x7eHuEe4B7jHuIe5R7kHuce5h7pHuge6x7qHu0e7B7vHu4e8R7wHvMe8h71HvQe9x72Hvke+B77Hvoe/R78Hv8e/h4AHwgfAR8JHwIfCh8DHwsfBB8MHwUfDR8GHw4fBx8PHxAfGB8RHxkfEh8aHxMfGx8UHxwfFR8dHyAfKB8hHykfIh8qHyMfKx8kHywfJR8tHyYfLh8nHy8fMB84HzEfOR8yHzofMx87HzQfPB81Hz0fNh8+HzcfPx9AH0gfQR9JH0IfSh9DH0sfRB9MH0UfTR9RH1kfUx9bH1UfXR9XH18fYB9oH2EfaR9iH2ofYx9rH2QfbB9lH20fZh9uH2cfbx9wH7ofcR+7H3IfyB9zH8kfdB/KH3Ufyx92H9ofdx/bH3gf+B95H/kfeh/qH3sf6x98H/offR/7H4AfiB+BH4kfgh+KH4Mfix+EH4wfhR+NH4Yfjh+HH48fkB+YH5EfmR+SH5ofkx+bH5QfnB+VH50flh+eH5cfnx+gH6gfoR+pH6Ifqh+jH6sfpB+sH6UfrR+mH64fpx+vH7AfuB+xH7kfsx+8H8MfzB/QH9gf0R/ZH+Af6B/hH+kf5R/sH/Mf/B9OITIhcCFgIXEhYSFyIWIhcyFjIXQhZCF1IWUhdiFmIXchZyF4IWgheSFpIXohaiF7IWshfCFsIX0hbSF+IW4hfyFvIYQhgyHQJLYk0SS3JNIkuCTTJLkk1CS6JNUkuyTWJLwk1yS9JNgkviTZJL8k2iTAJNskwSTcJMIk3STDJN4kxCTfJMUk4CTGJOEkxyTiJMgk4yTJJOQkyiTlJMsk5iTMJOckzSToJM4k6STPJDAsACwxLAEsMiwCLDMsAyw0LAQsNSwFLDYsBiw3LAcsOCwILDksCSw6LAosOywLLDwsDCw9LA0sPiwOLD8sDyxALBAsQSwRLEIsEixDLBMsRCwULEUsFSxGLBYsRywXLEgsGCxJLBksSiwaLEssGyxMLBwsTSwdLE4sHixPLB8sUCwgLFEsISxSLCIsUywjLFQsJCxVLCUsViwmLFcsJyxYLCgsWSwpLFosKixbLCssXCwsLF0sLSxeLC4sYSxgLGUsOgJmLD4CaCxnLGosaSxsLGsscyxyLHYsdSyBLIAsgyyCLIUshCyHLIYsiSyILIssiiyNLIwsjyyOLJEskCyTLJIslSyULJcsliyZLJgsmyyaLJ0snCyfLJ4soSygLKMsoiylLKQspyymLKksqCyrLKosrSysLK8sriyxLLAssyyyLLUstCy3LLYsuSy4LLssuiy9LLwsvyy+LMEswCzDLMIsxSzELMcsxizJLMgsyyzKLM0szCzPLM4s0SzQLNMs0izVLNQs1yzWLNks2CzbLNos3SzcLN8s3izhLOAs4yziLAAtoBABLaEQAi2iEAMtoxAELaQQBS2lEAYtphAHLacQCC2oEAktqRAKLaoQCy2rEAwtrBANLa0QDi2uEA8trxAQLbAQES2xEBItshATLbMQFC20EBUttRAWLbYQFy23EBgtuBAZLbkQGi26EBstuxAcLbwQHS29EB4tvhAfLb8QIC3AECEtwRAiLcIQIy3DECQtxBAlLcUQQaZApkOmQqZFpkSmR6ZGpkmmSKZLpkqmTaZMpk+mTqZRplCmU6ZSplWmVKZXplamWaZYplumWqZdplymX6ZepmOmYqZlpmSmZ6ZmpmmmaKZrpmqmbaZspoGmgKaDpoKmhaaEpoemhqaJpoimi6aKpo2mjKaPpo6mkaaQppOmkqaVppSml6aWpiOnIqclpySnJ6cmpymnKKcrpyqnLacspy+nLqczpzKnNac0pzenNqc5pzinO6c6pz2nPKc/pz6nQadAp0OnQqdFp0SnR6dGp0mnSKdLp0qnTadMp0+nTqdRp1CnU6dSp1WnVKdXp1anWadYp1unWqddp1ynX6dep2GnYKdjp2KnZadkp2enZqdpp2ina6dqp22nbKdvp26neqd5p3yne6d/p36ngaeAp4OngqeFp4Snh6eGp4yni6dB/yH/Qv8i/0P/I/9E/yT/Rf8l/0b/Jv9H/yf/SP8o/0n/Kf9K/yr/S/8r/0z/LP9N/y3/Tv8u/0//L/9Q/zD/Uf8x/1L/Mv9T/zP/VP80/1X/Nf9W/zb/V/83/1j/OP9Z/zn/Wv86/w==';

let upcaseTableCache: Uint16Array | null = null;
let upcaseBufferCache: Uint8Array | null = null;

export function getNtfsUpcaseTable(): Uint16Array {
  if (!upcaseTableCache) {
    const table = new Uint16Array(65536);
    for (let cp = 0; cp < 65536; cp++) {
      table[cp] = cp;
    }

    const binStr = atob(NT_UPCASE_PAIRS_B64);
    const count = binStr.length / 4;
    for (let i = 0; i < count; i++) {
      const src = binStr.charCodeAt(i * 4) | (binStr.charCodeAt(i * 4 + 1) << 8);
      const dst = binStr.charCodeAt(i * 4 + 2) | (binStr.charCodeAt(i * 4 + 3) << 8);
      table[src] = dst;
    }

    upcaseTableCache = table;
  }
  return upcaseTableCache;
}

export function generateNtfsUpcaseBuffer(): Uint8Array {
  if (!upcaseBufferCache) {
    const table = getNtfsUpcaseTable();
    const buf = new Uint8Array(128 * 1024);
    const view = new DataView(buf.buffer);
    for (let i = 0; i < 65536; i++) {
      view.setUint16(i * 2, table[i], true);
    }
    upcaseBufferCache = buf;
  }
  return upcaseBufferCache;
}

export function compareNtfsFileNames(a: string, b: string): number {
  const upcase = getNtfsUpcaseTable();
  const minLen = Math.min(a.length, b.length);
  for (let i = 0; i < minLen; i++) {
    const uca = upcase[a.charCodeAt(i)] ?? a.charCodeAt(i);
    const ucb = upcase[b.charCodeAt(i)] ?? b.charCodeAt(i);
    if (uca !== ucb) return uca - ucb;
  }
  return a.length - b.length;
}
